### ISSUE TITLE
input coordinates more than 1 or less than 0 return a value of 0

### ISSUE THREAD

**Issue by RugnirViking** [salaxieb/perlin_noise#3]
to test:
` print(noise([4, -2])) # should not == 0.0`

Allowing for this kind of usage is very useful for many applicatons, for example procedural texture animation.

**Comment by salaxieb** [comment]
Algorithm made in such a way that for integers with octaves=1 you will get
zeros
Choose another value for octaves, for example 1.3 or some irrational number,
and you will never get 0 for integer input

пт, 18 февр. 2022 г., 02:45 Samuel Howell ***@***.***>:

**Comment by salaxieb** [comment]
```
from perlin_noise import PerlinNoise
noise = PerlinNoise(octaves=1.32, seed=777)
noise([4, -2])
 -> 0.29462607177392364
```
