### ISSUE TITLE
what are the upper and lower bounds of noise?

### ISSUE THREAD

**Issue by lanyusan** [salaxieb/perlin_noise#4]
As in the title.

Are they [-1,1] inclusive?

Or you lib does no normalization and it is [− squareroot(N/4),squareroot(N/4) ] where N is number of dimensions?

p5js noise bound is normailzied to 0, 1.

Thanks

**Comment by salaxieb** [comment]
Hi, lanyusan!
Noise is not limited in dimensions and space size, [-inf, + inf]
Try as ex.
```
noise = PerlinNoise()
noise([+100.5, -1000.5, +10000.5, -10.6, 0, 0, 0, 0.1])
``` 

if you want to avoid noise([int, int, ..., int]) == 0
use irrational number as octaves
```
from math import pi
noise = PerlinNoise(octaves=pi)
noise([1, 2, 3, 10]) != 0
# --> True
```

[− squareroot(N/4),squareroot(N/4) ]  - no normalization, just sum for increasing number of spaces

**Comment by lanyusan** [comment]
Thanks

**Comment by Quadrum1** [comment]
I am sampling 5 different grids of perlin noise for each point.
Each grid has a different gradient assigned to it.
The grid of the 5 that has the highest value will be chosen as the final value of the point at x,y.
The result of this on a 200x200 grid is the following:
![SampleA](https://user-images.githubusercontent.com/38959426/174193697-47b9fe85-6b32-4421-b2bc-a5fe53960718.png)

This is supposed to be implemented in a use case, however, where there is no upper bound of that 200x200 grid. An infinite grid, you could say.
Trying to apply the above fix of using pi as the octave strength, and therefor removing the limiter to allow values greater than 1 into the noise function, however, yields the following:
![SampleA](https://user-images.githubusercontent.com/38959426/174193959-8d924847-7e62-4d55-8f5a-0e38f2356295.png)

There is no uniformity in the perlin noise any more, when the only thing I changed was removing the limit, which is not what I want to achieve.
Any idea of how to fix this?

**Comment by neale** [comment]
@lanyusan I guess processing's (p5) implementation of `noise()` is not perlin noise at all, even though they claim it is. The team is aware of this but they're keeping it for legacy reasons. Perlin noise output range is correctly given by @salaxieb . See the issue here

https://github.com/processing/processing/issues/2550
