### ISSUE TITLE
batched noise outputs

### ISSUE THREAD

**Issue by neale** [salaxieb/perlin_noise#5]
Hi,  is there any way to get more than one noise value at a time? 

For instance, if I wanted to generate a grid of size (10, 10), right now I need to use a double for loop to generate noise points one by one.
It would be ideal to batch this in some way so that `noise` could take a numpy array of coordinates and return the corresponding noise values. Do you have any ideas on how to do this?

**Comment by salaxieb** [comment]
### Give me, please, example of interface
### You want to pass coordinates as list of tuples?
### Because, right now if you pass list as input, it will return noise value for that coordinated
--
p.s. If you want to avoid double for loop, use list comprehension instead
p.s.s if you need to have a lot of intermediate points, try to approximate values manually, linearly of with sin function

**Comment by neale** [comment]
Well, currently the noise class expects a list of N components that describe a single coordinate in N-dimensional space. 
That's fine, but since Perlin noise is defined everywhere, it would be nice to have a similar function that took a multidimensional array (like a numpy ndarray) of coordinates, and returned the Perlin noise values at those locations. 
So, this function would take a 2d list or numpy.ndarray and return the corresponding Perlin noise points.
 
* List comprehension is fine, but not really what I meant. Besides, if you time it, list comprehension is not faster at all. 
* Interpolation is ok, but at that point, I'd probably just use simplex noise since it's cheaper to generate. 

Anyway, I was just wondering if it's currently possible with this implementation. But it sounds like it's not.

**Comment by salaxieb** [comment]
I have checked possibility to make batched noise output, and turns out that it will move for loop inside library and you will not get any increase in speed.
