### ISSUE TITLE
Stripes on generated iamges

### ISSUE THREAD

**Issue by kovtun77** [salaxieb/perlin_noise#6]
Test example to show error:

    import cv2
    import numpy as np
    from perlin_noise import PerlinNoise

    noise = PerlinNoise(octaves=160 / 87, seed=10)
    picture = np.array([[noise([j / 160, i / 160]) for j in range(160)] for i in range(160)])
    cv2.imwrite("stripes.png", 255*(0.5+picture))

![image](https://user-images.githubusercontent.com/17911760/203662591-8a005e49-66b2-463f-8f2c-3fc0c7d99403.png)

There might be a rounding error in this code that leads to the vertical and horizontal stripes on the image when coordiante is almost1 :

        coor_bounding_box = [
            (math.floor(coordinate), math.floor(coordinate + 1))
            for coordinate in coordinates
        ]

It is better to use

    (math.floor(coordinate), math.floor(coordinate) + 1)

**Comment by salaxieb** [comment]
This a really neat solution! Thanks!
see https://github.com/salaxieb/perlin_noise/pull/10
I'm sorry for a reply after 1.5 years after creation, I haven't received any notification from github about open issues...
My bad, thanks for using and fixing errors
