### ISSUE TITLE
Tilable noise

### ISSUE THREAD

**Issue by gordon13** [salaxieb/perlin_noise#9]
I haven't found a way to make the noise tilable. Maybe I'm missing something? If not, then I would definitely suggest adding this as a feature! It would be very useful for games and animation purposes to be able to be able to do this.

**Comment by salaxieb** [comment]
CHeckout the latest version, which supports tiles, examples can be found in README.md
Thanks for support and interest to project
Sorry for such a long answer, I didn't receive any notification from .github
Thanks for you cintribution

**Comment by salaxieb** [comment]
solved in commits:
1dbd9700ae08822058d42b3c228f2a7d6f1d43f1
bd74d42380ec5ec6f00b3be1b17353ae40448d45
7e20db412669f33134bdb13e2bd9fb9e27c50dfb
